schemas:
  Error:
    type: object
    required:
    - error
    properties:
      error:
        type: string
        description: "Error message"
        example: "Resource not found"
      errors:
        type: array
        description: "List of specific validation errors"
        items:
          type: object
          properties:
            field:
              type: string
              description: "Field with the error"
              example: "email"
            message:
              type: string
              description: "Error message for the field"
              example: "Email is invalid"
