schemas:
  Post:
    type: object
    required:
    - id
    - title
    - content
    - user_id
    - published
    properties:
      id:
        type: integer
        format: int64
        description: "Unique identifier for the post"
        example: 123
      title:
        type: string
        description: "Title of the blog post"
        example: "Getting Started with OpenAPI"
      content:
        type: string
        description: "Content of the blog post"
        example: "This is the main content of the blog post..."
      user_id:
        type: integer
        format: int64
        description: "ID of the user who created the post"
        example: 42
      author:
        $ref: "#/components/schemas/User"
        description: "The user who created the post"
      published:
        type: boolean
        description: "Whether the post is publicly visible"
        default: false
        example: true
      tags:
        type: array
        description: "List of tags associated with the post"
        items:
          type: string
        example: [ "api", "documentation" ]
      created_at:
        type: string
        format: date-time
        description: "Timestamp when the post was created"
        example: "2023-01-15T14:30:00Z"
      updated_at:
        type: string
        format: date-time
        description: "Timestamp when the post was last updated"
        example: "2023-01-20T09:15:00Z"
