# Validates that the model has a non-blank name attribute, failing validation if missing or empty. Defaults to true
require_name: true

# Validates that the model has a non-blank description attribute, failing validation if missing or empty. Defaults to true
require_description: true
