info:
  title: SpecForge Demo API
  version: 1.0.0
  description: |
    A demo API to showcase SpecForge's OpenAPI generation capabilities.
    This API includes endpoints for managing users, blog posts, and comments.
  contact:
    name: Bryan
    email: bryan@itsthedevman.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
- url: https://devapi.itsthedevman.com
  description: Development server
- url: https://prodapi.itsthedevman.com
  description: Production server

tags:
- name: users
  description: User account management
  externalDocs:
    url: "https://docs.prodapi.itsthedevman.com"
    description: "Internal user account management"
- name: posts
  description: Blog post management
- name: comments
  description: Comment management for blog posts
- name: content
  description: Content management operations
