info:
  title: SpecForge Integration Tests
  version: 0.0.1
  description: These are SpecForge's official integration tests
  contact:
    name: Bryan
    email: bryan@itsthedevman.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
- url: http://localhost:3000
  description: Testing

# tags:
#   users: User management
#   posts: Post management
#
# security_schemes:
#   bearer_auth:
#     type: http
#     scheme: bearer
#     bearer_format: JWT
