info:
  title: SpecForge Demo API
  version: 1.0.0
  description: |
    A demo API to showcase SpecForge's OpenAPI generation capabilities.
    This API includes endpoints for managing users, blog posts, and comments.
  contact:
    name: Bryan
    email: bryan@itsthedevman.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
- url: http://localhost:3000
  description: Local development server
- url: https://api.example.com/v1
  description: Production server

tags:
  Users:
    description: User account management
    external_docs:
      url: "https://localhost:3001"
      description: "Internal user account management"
  Posts:
    description: Blog post management
  Comments:
    description: Comment management for blog posts
  Content:
    description: Content management operations

security_schemes:
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT
