name: Tests

on:
  push:
    branches:
    - main
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
        - "3.2.7"
        - "3.3.7"
        - "3.4.2"
      fail-fast: false

    # Add PostgreSQL service for the tests
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: spec_forge
          POSTGRES_USER: password12345
          POSTGRES_DB: spec_forge
        ports:
        - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run RSpec
      run: bin/rspec
    - name: Setup
      run: spec/integration/bin/setup
    - name: Run Integration Tests
      run: spec/integration/bin/test
      env:
        RAILS_ENV: development
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/spec_forge
