name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # Main unit tests
  unit:
    runs-on: ubuntu-latest
    name: Unit Tests (Ruby ${{ matrix.ruby }})
    strategy:
      matrix:
        include:
          - ruby: "3.2"
            gemfile: gemfiles/ruby_3_2.gemfile
          - ruby: "3.3"
            gemfile: gemfiles/ruby_3_3.gemfile
          - ruby: "3.4"
            gemfile: Gemfile
      fail-fast: false

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}

    ##############################################
    steps:
      - uses: actions/checkout@v6
      ######
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      ######
      - name: Run tests
        run: bin/test
      ######
      - name: Run Standard
        run: bin/rake standard
    ##############################################
